"""C# language engine - .NET SDK + xUnit + coverlet.

Toolchain is the .NET SDK (10+) alone. xUnit and coverlet.collector are
fetched from NuGet by the scaffolded test project (same posture as Java's
JUnit-from-Maven-Central and Go's `go get`: declared build deps may be
fetched at validation time). SDK 10 is the floor because the native
scanner runs via file-based `dotnet run csharp_scanner.cs`.

Layout
------
    widget_root/
      cartograph-deps.props    generated from widget.json deps (do not edit)
      src/<widget_id>.csproj   class library - the widget OWNS this file
      src/<Class>.cs           library sources, namespace <Class>Widget
      tests/Tests.csproj       xUnit + coverlet, references ../src
      tests/<Class>Tests.cs    black-box tests
      examples/Examples.csproj executable, references ../src
      examples/ExampleUsage.cs top-level-statements example

Widgets own their csproj files - including extra PropertyGroups and
build customization - so widgets that need analyzers or source
generators work without engine changes. The engine's only contract with
the build is: `dotnet test tests` produces a Cobertura coverage report
(via coverlet.collector), and `dotnet run --project examples` runs the
example.

Declared widget.json dependencies ("PackageId>=version") are written to
cartograph-deps.props by install_deps(), which the scaffolded src csproj
imports. NuGet PackageReference versions are floors natively, so the
declared floor maps 1:1. The engine never edits csproj files itself.

Coverage is enforced at 80% (Cobertura line-rate of the src assembly;
the test assembly is excluded by coverlet automatically). Widgets are
libraries: no Console printing, no Environment.Exit/FailFast, no
Thread.Sleep in src/.
"""

import glob as _glob
import os
import re
import shutil as _shutil

from .base import LanguageEngine, _dep_bare_name

_COVERAGE_THRESHOLD = 80

_SRC_CSPROJ = """\
<Project Sdk="Microsoft.NET.Sdk">
  <!-- This widget owns this file. Add properties, analyzers, or source
       generators freely - Cartograph only requires that `dotnet test tests`
       produces a Cobertura coverage report and that the examples project
       runs the example. -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>{module}</AssemblyName>
    <RootNamespace>{ns}</RootNamespace>
  </PropertyGroup>
  <!-- Declared widget.json dependencies land in cartograph-deps.props -
       never edit that file or add PackageReferences here by hand. -->
  <Import Project="../cartograph-deps.props"
          Condition="Exists('../cartograph-deps.props')" />
</Project>
"""

_TESTS_CSPROJ = """\
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../src/{module}.csproj" />
  </ItemGroup>
</Project>
"""

_EXAMPLES_CSPROJ = """\
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../src/{module}.csproj" />
  </ItemGroup>
</Project>
"""

_DEPS_PROPS_HEADER = """\
<!-- Generated by Cartograph from widget.json tech_stack.dependencies.
     Do not edit - declare deps in widget.json instead. -->
<Project>
</Project>
"""

_CSHARP_SRC = """\
namespace {ns};

/// <summary>
/// {name}.
///
/// [TODO] Replace with the widget's real API. Public members are the
/// widget's public surface - document each one.
/// </summary>
public static class {cls}
{{
    /// <summary>Returns the input value.</summary>
    /// <param name="value">The input.</param>
    /// <returns>The same value.</returns>
    public static string Process(string value) => value;
}}
"""

_CSHARP_TEST = """\
using Xunit;
using {ns};

namespace Tests;

/// <summary>
/// Black-box tests for {name}. Imports the widget by namespace, exactly
/// as a consumer would.
/// </summary>
public class {cls}Tests
{{
    [Fact]
    public void ProcessReturnsInput()
    {{
        // [TODO] Replace with real tests. Coverage of src/ must reach {threshold}%.
        Assert.Equal("hello", {cls}.Process("hello"));
    }}
}}
"""

_CSHARP_EXAMPLE = """\
using {ns};

// Example usage of {name}.
//
// This must run and exit cleanly with no user input, no network calls,
// and no external services. Use fake/hardcoded data to demonstrate the
// API.

// [TODO] Replace with a realistic call using fake data
Console.WriteLine({cls}.Process("hello"));
"""

# The root element of a Cobertura report:
#   <coverage line-rate="0.8571" branch-rate="..." ...>
_COBERTURA_LINE_RATE_RE = re.compile(r'<coverage[^>]*\bline-rate="([\d.]+)"')

# "PackageId>=1.2.3" -> PackageReference Version="1.2.3" (NuGet floors)
_DEP_FLOOR_RE = re.compile(r">=\s*([\w.+-]+)")


def _pascal_name(module_name: str) -> str:
    """PascalCase identifier from a hyphen/underscore slug."""
    return "".join(p.capitalize() for p in re.split(r"[-_]+", module_name) if p)


class CSharpEngine(LanguageEngine):
    name = "csharp"
    validation_version = 1
    file_ext = "cs"
    aliases = ["cs", "c#", "dotnet"]
    toolchain = {
        "dotnet": "Install the .NET SDK 10+ - dotnet.microsoft.com/download",
    }
    supported = True

    scanner_runner = ["dotnet", "run"]
    scanner_messages = {
        "print": "Console printing found in src/ - widgets are libraries, remove console output:",
        "exit": "Environment.Exit/FailFast found in src/ - widgets must not exit the caller's process:",
    }
    scanner_warning_messages = {
        "credential": "Possible credentials found - remove before checkin:",
        "hardcoded_url": "Hardcoded URLs found - consider making these configurable:",
        "hardcoded_ip": "Hardcoded IPs found - consider making these configurable:",
        "hardcoded_value": "Hardcoded numeric tunables found in src/ - prefer parameters:",
        "abs_path": "Absolute paths found - widgets must be portable:",
        "env_var": "Environment variable access found in src/ - verify it's not project-specific:",
        "sleep": "Thread.Sleep found - widgets must not block the caller:",
        "unlisted_import": "Unlisted using imports - add to widget.json dependencies or remove:",
        "static_mutable": "Mutable static field found in src/ - prefer instance state or explicit parameters:",
    }
    import_pattern = r"^using\s"
    manifest_patterns = ["cartograph-deps.props", "src/*.csproj",
                        "tests/*.csproj", "examples/*.csproj"]

    # dotnet is a real executable on Windows - no cmd.exe reparse needed,
    # and shell=True would mangle args like `--collect "XPlat Code Coverage"`.
    windows_shell = False

    # ---- toolchain ---------------------------------------------------------

    # Cached SDK-major probe. File-based `dotnet run` (the native scanner's
    # runner) needs SDK 10+, so an older SDK counts as unavailable with a
    # targeted message rather than failing mid-validate. None = not probed.
    _sdk_major: int | None = None

    def check_available(self) -> tuple[bool, str]:
        ok, msg = super().check_available()
        if not ok:
            return ok, msg
        if CSharpEngine._sdk_major is None:
            ver = self.runtime_version() or ""
            m = re.search(r"(\d+)\.", ver)
            CSharpEngine._sdk_major = int(m.group(1)) if m else 0
        if CSharpEngine._sdk_major < 10:
            return False, (
                "C# engine requires .NET SDK 10+ (file-based `dotnet run` "
                "executes the contamination scanner) - found "
                f"SDK {CSharpEngine._sdk_major or 'unknown'}. Install from "
                "dotnet.microsoft.com/download (or set paths.dotnet in "
                "`cartograph config`)"
            )
        return True, ""

    def runtime_version(self) -> str | None:
        try:
            res = self._run(["dotnet", "--version"], cwd=".", timeout=30)
            ver = (res.stdout or "").strip()
            if res.returncode == 0 and ver:
                return f"dotnet {ver}"
        except Exception:
            pass
        return None

    # ---- scaffold ----------------------------------------------------------

    def scaffold(self, target_dir, module_name, display_name, **_):
        cls = _pascal_name(module_name)
        ns = f"{cls}Widget"

        def _w(path, content):
            with open(path, "w", newline="\n", encoding="utf-8") as f:
                f.write(content)

        for d in ("src", "tests", "examples"):
            os.makedirs(os.path.join(target_dir, d), exist_ok=True)
        _w(os.path.join(target_dir, "cartograph-deps.props"),
           _DEPS_PROPS_HEADER)
        _w(os.path.join(target_dir, "src", f"{module_name}.csproj"),
           _SRC_CSPROJ.format(module=module_name, ns=ns))
        _w(os.path.join(target_dir, "src", f"{cls}.cs"),
           _CSHARP_SRC.format(ns=ns, cls=cls, name=display_name))
        _w(os.path.join(target_dir, "tests", "Tests.csproj"),
           _TESTS_CSPROJ.format(module=module_name))
        _w(os.path.join(target_dir, "tests", f"{cls}Tests.cs"),
           _CSHARP_TEST.format(ns=ns, cls=cls, name=display_name,
                               threshold=_COVERAGE_THRESHOLD))
        _w(os.path.join(target_dir, "examples", "Examples.csproj"),
           _EXAMPLES_CSPROJ.format(module=module_name))
        _w(os.path.join(target_dir, "examples", "ExampleUsage.cs"),
           _CSHARP_EXAMPLE.format(ns=ns, cls=cls, name=display_name))

    def find_test_files(self, path: str) -> list[str]:
        return _glob.glob(os.path.join(path, "tests", "**", "*Tests.cs"),
                          recursive=True)

    def example_filename(self, path: str = "") -> str:
        return "ExampleUsage.cs"

    def required_files(self, path: str) -> list[tuple[str, str]]:
        missing = []
        for sub, hint in (("src", "class library"),
                          ("tests", "xUnit test project"),
                          ("examples", "example executable")):
            if not _glob.glob(os.path.join(path, sub, "*.csproj")):
                missing.append(
                    (f"{sub}/*.csproj",
                     f"A {hint} .csproj is required in {sub}/ - run "
                     "'cartograph create' to scaffold it"))
        return missing

    # ---- validation (build check on top of base scanner pipeline) ----------

    def validate_widget(self, path: str, dependencies: list) -> dict:
        errors = []

        src_files = _glob.glob(os.path.join(path, "src", "**", "*.cs"),
                               recursive=True)
        if not src_files:
            errors.append("src/ contains no .cs files - add at least one "
                          "source file")

        if src_files and _glob.glob(os.path.join(path, "src", "*.csproj")):
            # Build src/ only: a type error should fail validation with a
            # compiler message, not surface later as a confusing test
            # failure. validate runs before install_deps in the pipeline,
            # so write the declared deps into cartograph-deps.props first -
            # restore resolves them during the build. Resolution failures
            # (offline, feed hiccup - NuGet NU1xxx errors) are skipped
            # here; run_tests catches genuinely missing deps after install.
            self._write_deps_props(path, dependencies)
            try:
                res = self._run(["dotnet", "build", "src", "--nologo",
                                 "-v", "quiet"], cwd=path, timeout=300)
                if res.returncode != 0:
                    output = (res.stdout or "") + (res.stderr or "")
                    output = output.strip()
                    if not re.search(r"\bNU1\d+\b", output) \
                            and "service index" not in output:
                        errors.append(f"dotnet build src failed:\n"
                                      f"{output[:3000]}")
            except FileNotFoundError:
                errors.append("dotnet not found - install the .NET SDK 10+ "
                              "(dotnet.microsoft.com/download).")

        scanner = os.path.join(os.path.dirname(__file__), "scanners",
                               "csharp_scanner.cs")
        scan_errors, _, _ = self._run_native_scanner(
            scanner_path=scanner,
            runner=self.scanner_runner,
            src_files=src_files,
            cwd=path,
            finding_messages=self.scanner_messages,
        )
        errors.extend(scan_errors)

        errors.extend(self._check_dep_pinning(dependencies))

        if errors:
            return self._fail("\n".join(errors))
        return self._ok()

    def scan_contamination(self, path: str, widget: dict) -> dict:
        all_files = []
        for sub in ("src", "tests", "examples"):
            all_files.extend(_glob.glob(
                os.path.join(path, sub, "**", "*.cs"), recursive=True))
        scanner = os.path.join(os.path.dirname(__file__), "scanners",
                               "csharp_scanner.cs")
        scan_errors, scan_warnings, scan_blocks = self._run_native_scanner(
            scanner_path=scanner,
            runner=self.scanner_runner,
            src_files=all_files,
            cwd=path,
            finding_messages=self.scanner_messages,
        )
        return {"blocks": scan_blocks + scan_errors,
                "warnings": scan_warnings}

    # ---- dependencies ------------------------------------------------------

    def install_deps(self, path: str, dependencies: list) -> None:
        """Write declared deps to cartograph-deps.props and restore them.

        Dependency format: "PackageId>=version", e.g.
        "Newtonsoft.Json>=13.0.3". NuGet PackageReference versions are
        floors natively, so the declared floor becomes the Version
        attribute unchanged. The shared NuGet cache (~/.nuget) is
        checksummed per package, so no per-widget isolation is needed.
        """
        self._write_deps_props(path, dependencies)
        if not dependencies:
            return
        res = self._run(["dotnet", "restore", "src"], cwd=path, timeout=300)
        if res.returncode != 0:
            output = ((res.stdout or "") + (res.stderr or "")).strip()
            raise RuntimeError(
                f"Failed to resolve C# dependencies:\n{output[:2000]}")

    # ---- tests + coverage --------------------------------------------------

    def run_tests(self, path: str) -> dict:
        if not self.find_test_files(path):
            return self._fail("No *Tests.cs files found in tests/")

        results_dir = os.path.join(path, "TestResults")
        try:
            res = self._run(["dotnet", "test", "tests", "--nologo",
                             "-v", "minimal",
                             "--collect", "XPlat Code Coverage",
                             "--results-directory", results_dir],
                            cwd=path, timeout=600)
        except FileNotFoundError:
            return self._fail("dotnet not found - install the .NET SDK 10+ "
                              "(dotnet.microsoft.com/download).")
        if res.returncode != 0:
            return self._fail(res.stdout or res.stderr)

        reports = _glob.glob(os.path.join(results_dir, "**",
                                          "coverage.cobertura.xml"),
                             recursive=True)
        if not reports:
            return self._fail(
                "Cobertura coverage report not found after tests - the "
                "widget's tests/Tests.csproj must keep the "
                "coverlet.collector package (see the scaffolded "
                "Tests.csproj)")
        # Newest report wins if stale runs left extras behind.
        report = max(reports, key=os.path.getmtime)
        with open(report, encoding="utf-8") as f:
            m = _COBERTURA_LINE_RATE_RE.search(f.read())
        if not m:
            return self._fail("Could not determine coverage from the "
                              "Cobertura report - no line-rate found")
        pct = float(m.group(1)) * 100.0
        if pct < _COVERAGE_THRESHOLD:
            return self._fail(
                f"Coverage {pct:.1f}% is below the required "
                f"{_COVERAGE_THRESHOLD}% - add tests for the uncovered "
                f"lines (open the coverage.cobertura.xml under "
                f"TestResults/ for a per-class breakdown)")
        return self._ok()

    # ---- example -----------------------------------------------------------

    def run_example(self, path: str) -> dict:
        if not os.path.isfile(os.path.join(path, "examples",
                                           self.example_filename())):
            return self._fail("examples/ExampleUsage.cs not found")
        try:
            res = self._run(["dotnet", "run", "--project", "examples"],
                            cwd=path, timeout=300)
        except FileNotFoundError:
            return self._fail("dotnet not found - install the .NET SDK 10+ "
                              "(dotnet.microsoft.com/download).")
        if res.returncode != 0:
            return self._fail(res.stderr or res.stdout)
        return self._ok()

    # ---- cleanup -----------------------------------------------------------

    def cleanup(self, path: str) -> None:
        for d in ("TestResults",
                  os.path.join("src", "bin"), os.path.join("src", "obj"),
                  os.path.join("tests", "bin"), os.path.join("tests", "obj"),
                  os.path.join("examples", "bin"),
                  os.path.join("examples", "obj")):
            full = os.path.join(path, d)
            if os.path.isdir(full):
                _shutil.rmtree(full, ignore_errors=True)
        self._cleanup_artifact_dirs(path)

    # ---- private -----------------------------------------------------------

    def _run(self, cmd, cwd, timeout=60, env=None):
        """All dotnet invocations run quiet: no telemetry, no first-run
        banner, English diagnostics for stable error matching."""
        env = dict(env or os.environ)
        env.setdefault("DOTNET_CLI_TELEMETRY_OPTOUT", "1")
        env.setdefault("DOTNET_NOLOGO", "1")
        env.setdefault("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", "1")
        env.setdefault("DOTNET_CLI_UI_LANGUAGE", "en")
        # Leave no daemons behind (the Gradle --no-daemon lesson): no
        # MSBuild node reuse, no persistent MSBuild server, no shared
        # Roslyn compiler server. MSBuild reads env vars as global
        # properties, so UseSharedCompilation applies everywhere.
        env.setdefault("MSBUILDDISABLENODEREUSE", "1")
        env.setdefault("DOTNET_CLI_USE_MSBUILD_SERVER", "0")
        env.setdefault("UseSharedCompilation", "false")
        return super()._run(cmd, cwd=cwd, timeout=timeout, env=env)

    @staticmethod
    def _write_deps_props(path: str, dependencies: list) -> None:
        """Regenerate cartograph-deps.props from the declared deps."""
        lines = [
            "<!-- Generated by Cartograph from widget.json "
            "tech_stack.dependencies.\n",
            "     Do not edit - declare deps in widget.json instead. -->\n",
            "<Project>\n",
        ]
        refs = []
        for dep in dependencies or []:
            bare = _dep_bare_name(dep)
            if not bare:
                continue
            m = _DEP_FLOOR_RE.search(str(dep))
            version = f' Version="{m.group(1)}"' if m else ""
            refs.append(f'    <PackageReference Include="{bare}"'
                        f'{version} />\n')
        if refs:
            lines.append("  <ItemGroup>\n")
            lines.extend(refs)
            lines.append("  </ItemGroup>\n")
        lines.append("</Project>\n")
        with open(os.path.join(path, "cartograph-deps.props"), "w",
                  newline="\n", encoding="utf-8") as f:
            f.writelines(lines)
