"""Java language engine - Gradle + JUnit 5 + JaCoCo.

Toolchain is the JDK (21+) plus Gradle. JUnit 5 is fetched from Maven
Central by the scaffolded build (same posture as Go's `go get` and PHP's
Composer: declared build deps may be fetched at validation time). JaCoCo
is a Gradle core plugin, so coverage needs no extra system install.

Layout
------
    widget_root/
      settings.gradle          rootProject.name (stops Gradle walking up)
      build.gradle             the widget OWNS this file, plugins included
      cartograph-deps.gradle   generated from widget.json deps (do not edit)
      src/                     library sources, package <module_name>
      tests/                   black-box JUnit tests, package tests
      examples/                ExampleUsage.java - package examples, main()

Widgets own their full build.gradle - including the plugins block - so
builds that need build-time plugins (e.g. Fabric Loom for Minecraft mod
widgets) work without engine changes. The engine's only contract with
the build is: `test` produces a JaCoCo XML report, and a `runExample`
JavaExec task runs examples/ExampleUsage.java.

Declared widget.json dependencies ("group:artifact>=version") are written
to cartograph-deps.gradle by install_deps(), which the scaffolded
build.gradle applies. The engine never edits build.gradle itself.

Coverage is enforced at 80% (JaCoCo line counters). Widgets are
libraries: no System.out/err printing, no System.exit, no Thread.sleep
in src/.
"""

import glob as _glob
import os
import re
import shutil as _shutil

from .base import LanguageEngine, _dep_bare_name

_COVERAGE_THRESHOLD = 80

_SETTINGS_GRADLE = """\
rootProject.name = '{module}'
"""

_BUILD_GRADLE = """\
// This widget owns its build. Add plugins (e.g. Fabric Loom) and build
// logic freely - Cartograph only requires that `test` produces the
// JaCoCo XML report and that `runExample` runs the example.
plugins {{
    id 'java'
    id 'jacoco'
}}

repositories {{
    mavenCentral()
}}

sourceSets {{
    main {{
        java {{ srcDirs = ['src'] }}
    }}
    test {{
        java {{ srcDirs = ['tests'] }}
    }}
    example {{
        java {{ srcDirs = ['examples'] }}
        compileClasspath += sourceSets.main.output + configurations.runtimeClasspath
        runtimeClasspath += sourceSets.main.output + configurations.runtimeClasspath
    }}
}}

dependencies {{
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}}

// Declared widget.json dependencies land here - never edit by hand.
apply from: 'cartograph-deps.gradle'

test {{
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}}

jacocoTestReport {{
    reports {{
        xml.required = true
        html.required = false
    }}
}}

tasks.register('runExample', JavaExec) {{
    classpath = sourceSets.example.runtimeClasspath
    mainClass = 'examples.ExampleUsage'
}}
"""

_DEPS_GRADLE_HEADER = """\
// Generated by Cartograph from widget.json tech_stack.dependencies.
// Do not edit - declare deps in widget.json instead.
"""

_JAVA_SRC = """\
package {pkg};

/**
 * {name}.
 *
 * [TODO] Replace with the widget's real API. Public methods are the
 * widget's public surface - document each one.
 */
public final class {cls} {{

    private {cls}() {{
    }}

    /**
     * Returns the input value.
     *
     * @param value the input
     * @return the same value
     */
    public static String process(String value) {{
        return value;
    }}
}}
"""

_JAVA_TEST = """\
package tests;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import {pkg}.{cls};

/**
 * Black-box tests for {name}. Imports the widget by package, exactly as
 * a consumer would.
 */
class {cls}Test {{

    @Test
    void processReturnsInput() {{
        // [TODO] Replace with real tests. Coverage of src/ must reach {threshold}%.
        assertEquals("hello", {cls}.process("hello"));
    }}
}}
"""

_JAVA_EXAMPLE = """\
package examples;

import {pkg}.{cls};

/**
 * Example usage of {name}.
 *
 * <p>This must run and exit cleanly with no user input, no network
 * calls, and no external services. Use fake/hardcoded data to
 * demonstrate the API.
 */
public final class ExampleUsage {{

    private ExampleUsage() {{
    }}

    public static void main(String[] args) {{
        // [TODO] Replace with a realistic call using fake data
        System.out.println({cls}.process("hello"));
    }}
}}
"""

# The report-level (last) LINE counter in the JaCoCo XML:
#   <counter type="LINE" missed="2" covered="18"/>
_JACOCO_LINE_RE = re.compile(
    r'<counter type="LINE" missed="(\d+)" covered="(\d+)"/>')

# "group:artifact>=1.2.3" -> Gradle coordinate "group:artifact:1.2.3"
_DEP_FLOOR_RE = re.compile(r">=\s*([\w.+-]+)")


def _java_package_name(module_name: str) -> str:
    """Java identifiers can't contain hyphens; module slugs can."""
    return module_name.replace("-", "_")


def _java_class_name(module_name: str) -> str:
    """PascalCase class name from a hyphen/underscore slug."""
    return "".join(p.capitalize() for p in re.split(r"[-_]+", module_name) if p)


class JavaEngine(LanguageEngine):
    name = "java"
    validation_version = 1
    file_ext = "java"
    toolchain = {
        "java": "Install a JDK 21+ - adoptium.net",
        "gradle": "Install Gradle 8+ - gradle.org/install",
    }
    supported = True

    scanner_runner = ["java"]
    scanner_messages = {
        "print": "System.out/System.err printing found in src/ - widgets are libraries, remove console output:",
        "exit": "System.exit/Runtime.halt found in src/ - widgets must not exit the caller's process:",
    }
    scanner_warning_messages = {
        "credential": "Possible credentials found - remove before checkin:",
        "hardcoded_url": "Hardcoded URLs found - consider making these configurable:",
        "hardcoded_ip": "Hardcoded IPs found - consider making these configurable:",
        "hardcoded_value": "Hardcoded numeric tunables found in src/ - prefer parameters:",
        "abs_path": "Absolute paths found - widgets must be portable:",
        "env_var": "Environment variable access found in src/ - verify it's not project-specific:",
        "sleep": "Thread.sleep found - widgets must not block the caller:",
        "unlisted_import": "Unlisted package imports - add to widget.json dependencies or remove:",
        "static_mutable": "Non-final static field found in src/ - prefer instance state or explicit parameters:",
    }
    import_pattern = r"^import\s"
    manifest_patterns = ["build.gradle", "settings.gradle",
                         "cartograph-deps.gradle"]

    # gradle on Windows is gradle.bat - needs the shell (base default True).

    # ---- toolchain ---------------------------------------------------------

    # Cached result of the functional `java -version` probe. macOS ships a
    # /usr/bin/java stub that exists on PATH with no JDK installed - it only
    # prints "Unable to locate a Java Runtime". PATH resolution alone is a
    # lie there, so availability must actually run the binary. None = not
    # probed yet.
    _java_probe_ok: bool | None = None

    def check_available(self) -> tuple[bool, str]:
        ok, msg = super().check_available()
        if not ok:
            return ok, msg
        if JavaEngine._java_probe_ok is None:
            JavaEngine._java_probe_ok = self.runtime_version() is not None
        if not JavaEngine._java_probe_ok:
            return False, (
                "Java engine requires a working JDK - the `java` binary on "
                "PATH could not report a version (on macOS this is Apple's "
                "no-JDK stub). Install a JDK 21+ - adoptium.net "
                "(or set paths.java in `cartograph config`)"
            )
        return True, ""

    def runtime_version(self) -> str | None:
        try:
            res = self._run(["java", "-version"], cwd=".", timeout=15)
            # java -version prints to stderr:  openjdk version "21.0.11" ...
            m = re.search(r'version "([^"]+)"', res.stderr or res.stdout or "")
            if m:
                return f"java {m.group(1)}"
        except Exception:
            pass
        return None

    # ---- scaffold ----------------------------------------------------------

    def scaffold(self, target_dir, module_name, display_name, **_):
        pkg = _java_package_name(module_name)
        cls = _java_class_name(module_name)

        def _w(path, content):
            with open(path, "w", newline="\n", encoding="utf-8") as f:
                f.write(content)

        _w(os.path.join(target_dir, "settings.gradle"),
           _SETTINGS_GRADLE.format(module=module_name))
        _w(os.path.join(target_dir, "build.gradle"), _BUILD_GRADLE)
        _w(os.path.join(target_dir, "cartograph-deps.gradle"),
           _DEPS_GRADLE_HEADER)
        for d in ("src", "tests", "examples"):
            os.makedirs(os.path.join(target_dir, d), exist_ok=True)
        _w(os.path.join(target_dir, "src", f"{cls}.java"),
           _JAVA_SRC.format(pkg=pkg, cls=cls, name=display_name))
        _w(os.path.join(target_dir, "tests", f"{cls}Test.java"),
           _JAVA_TEST.format(pkg=pkg, cls=cls, name=display_name,
                             threshold=_COVERAGE_THRESHOLD))
        _w(os.path.join(target_dir, "examples", "ExampleUsage.java"),
           _JAVA_EXAMPLE.format(pkg=pkg, cls=cls, name=display_name))

    def find_test_files(self, path: str) -> list[str]:
        return _glob.glob(os.path.join(path, "tests", "**", "*Test.java"),
                          recursive=True)

    def example_filename(self, path: str = "") -> str:
        return "ExampleUsage.java"

    def required_files(self, path: str) -> list[tuple[str, str]]:
        missing = []
        for fname in ("build.gradle", "settings.gradle"):
            if not os.path.isfile(os.path.join(path, fname)):
                missing.append(
                    (fname,
                     f"A {fname} file is required at the widget root - run "
                     "'cartograph create' to scaffold it"))
        return missing

    # ---- validation (compile check on top of base scanner pipeline) --------

    def validate_widget(self, path: str, dependencies: list) -> dict:
        errors = []

        src_files = _glob.glob(os.path.join(path, "src", "**", "*.java"),
                               recursive=True)
        if not src_files:
            errors.append("src/ contains no .java files - add at least one "
                          "source file")

        if src_files:
            # Compile src/ only: a type error should fail validation with a
            # javac message, not surface later as a confusing test failure.
            # validate runs before install_deps in the pipeline, so write
            # the declared deps into cartograph-deps.gradle first - Gradle
            # resolves them itself during the compile. Resolution failures
            # (offline, registry hiccup) are still skipped here; run_tests
            # catches genuinely missing deps after install.
            self._write_deps_gradle(path, dependencies)
            try:
                res = self._run(self._gradle_cmd("compileJava"), cwd=path,
                                timeout=300)
                if res.returncode != 0:
                    output = (res.stderr or res.stdout or "").strip()
                    mismatch = self._toolchain_mismatch(output)
                    if mismatch:
                        errors.append(mismatch)
                    elif "Could not resolve" not in output \
                            and "Could not find" not in output:
                        errors.append(f"gradle compileJava failed:\n"
                                      f"{output[:3000]}")
            except FileNotFoundError:
                errors.append("Gradle not found - install Gradle 8+ "
                              "(gradle.org/install).")

        scanner = os.path.join(os.path.dirname(__file__), "scanners",
                               "java_scanner.java")
        scan_errors, _, _ = self._run_native_scanner(
            scanner_path=scanner,
            runner=self.scanner_runner,
            src_files=src_files,
            cwd=path,
            finding_messages=self.scanner_messages,
        )
        errors.extend(scan_errors)

        errors.extend(self._check_dep_pinning(dependencies))

        if errors:
            return self._fail("\n".join(errors))
        return self._ok()

    def scan_contamination(self, path: str, widget: dict) -> dict:
        all_files = []
        for sub in ("src", "tests", "examples"):
            all_files.extend(_glob.glob(
                os.path.join(path, sub, "**", "*.java"), recursive=True))
        scanner = os.path.join(os.path.dirname(__file__), "scanners",
                               "java_scanner.java")
        scan_errors, scan_warnings, scan_blocks = self._run_native_scanner(
            scanner_path=scanner,
            runner=self.scanner_runner,
            src_files=all_files,
            cwd=path,
            finding_messages=self.scanner_messages,
        )
        return {"blocks": scan_blocks + scan_errors,
                "warnings": scan_warnings}

    # ---- dependencies ------------------------------------------------------

    def install_deps(self, path: str, dependencies: list) -> None:
        """Write declared deps to cartograph-deps.gradle and resolve them.

        Dependency format: "group:artifact>=version", e.g.
        "com.google.code.gson:gson>=2.11.0". The floor becomes the Gradle
        coordinate version (consumers can raise it). Gradle's shared module
        cache (~/.gradle) is checksummed per coordinate, so no per-widget
        isolation is needed.
        """
        self._write_deps_gradle(path, dependencies)
        if not dependencies:
            return
        res = self._run(self._gradle_cmd("dependencies",
                                         "--configuration",
                                         "runtimeClasspath"),
                        cwd=path, timeout=300)
        if res.returncode != 0:
            output = (res.stderr or res.stdout or "").strip()
            mismatch = self._toolchain_mismatch(output)
            if mismatch:
                raise RuntimeError(mismatch)
            raise RuntimeError(
                f"Failed to resolve Java dependencies:\n{output[:2000]}")

    # ---- tests + coverage --------------------------------------------------

    def run_tests(self, path: str) -> dict:
        if not self.find_test_files(path):
            return self._fail("No *Test.java files found in tests/")

        try:
            res = self._run(self._gradle_cmd("test"), cwd=path, timeout=600)
        except FileNotFoundError:
            return self._fail("Gradle not found - install Gradle 8+ "
                              "(gradle.org/install).")
        if res.returncode != 0:
            output = (res.stdout or "") + (res.stderr or "")
            mismatch = self._toolchain_mismatch(output)
            if mismatch:
                return self._fail(mismatch)
            return self._fail(res.stdout or res.stderr)

        report = os.path.join(path, "build", "reports", "jacoco", "test",
                              "jacocoTestReport.xml")
        if not os.path.isfile(report):
            return self._fail(
                "JaCoCo XML report not found after tests - the widget's "
                "build.gradle must keep the jacoco plugin with "
                "xml.required = true (see the scaffolded build.gradle)")
        with open(report, encoding="utf-8") as f:
            xml = f.read()
        counters = _JACOCO_LINE_RE.findall(xml)
        if not counters:
            return self._fail("Could not determine coverage from the JaCoCo "
                              "report - no LINE counters found")
        # The report-level counter is the last one in the document.
        missed, covered = (int(v) for v in counters[-1])
        total = missed + covered
        pct = 100.0 * covered / total if total else 0.0
        if pct < _COVERAGE_THRESHOLD:
            return self._fail(
                f"Coverage {pct:.1f}% is below the required "
                f"{_COVERAGE_THRESHOLD}% - add tests for the uncovered "
                f"lines (re-run with html.required = true in "
                f"jacocoTestReport for a per-class breakdown)")
        return self._ok()

    # ---- example -----------------------------------------------------------

    def run_example(self, path: str) -> dict:
        if not os.path.isfile(os.path.join(path, "examples",
                                           self.example_filename())):
            return self._fail("examples/ExampleUsage.java not found")
        try:
            res = self._run(self._gradle_cmd("runExample"), cwd=path,
                            timeout=300)
        except FileNotFoundError:
            return self._fail("Gradle not found - install Gradle 8+ "
                              "(gradle.org/install).")
        if res.returncode != 0:
            output = (res.stdout or "") + (res.stderr or "")
            mismatch = self._toolchain_mismatch(output)
            if mismatch:
                return self._fail(mismatch)
            return self._fail(res.stderr or res.stdout)
        return self._ok()

    # ---- cleanup -----------------------------------------------------------

    def cleanup(self, path: str) -> None:
        for d in ("build", ".gradle"):
            full = os.path.join(path, d)
            if os.path.isdir(full):
                _shutil.rmtree(full, ignore_errors=True)
        self._cleanup_artifact_dirs(path)

    # ---- private -----------------------------------------------------------

    @staticmethod
    def _write_deps_gradle(path: str, dependencies: list) -> None:
        """Regenerate cartograph-deps.gradle from the declared deps."""
        lines = [_DEPS_GRADLE_HEADER, "dependencies {\n"]
        for dep in dependencies or []:
            bare = _dep_bare_name(dep)
            if not bare or ":" not in bare:
                continue
            m = _DEP_FLOOR_RE.search(str(dep))
            coord = f"{bare}:{m.group(1)}" if m else bare
            lines.append(f"    implementation '{coord}'\n")
        lines.append("}\n")
        with open(os.path.join(path, "cartograph-deps.gradle"), "w",
                  newline="\n", encoding="utf-8") as f:
            f.writelines(lines)

    @staticmethod
    def _toolchain_mismatch(output: str) -> str:
        """Detect a JDK too new for the installed Gradle.

        Gradle's embedded Groovy rejects class files newer than it knows
        ("Unsupported class file major version N", e.g. 69 = JDK 25 vs
        Gradle 8.x). That is a toolchain incompatibility, not a widget
        content failure - report it as such instead of blaming the code.
        """
        m = re.search(r"Unsupported class file major version (\d+)",
                      output or "")
        if not m:
            return ""
        jdk = int(m.group(1)) - 44  # class file major = Java version + 44
        return (f"Your JDK (Java {jdk}) is newer than the installed Gradle "
                f"supports. Use JDK 21 LTS, or upgrade Gradle to a release "
                f"that supports Java {jdk} "
                f"(docs.gradle.org/current/userguide/compatibility.html).")

    @staticmethod
    def _gradle_cmd(*tasks: str) -> list:
        """Gradle invocation with a quiet, CI-safe argument set.

        --no-daemon: never leave a JVM behind in sandboxes/CI runners.
        --console=plain: no ANSI control sequences in captured output.
        """
        return ["gradle", "--no-daemon", "--console=plain", *tasks]
